"""
Pepperland — the demo jurisdiction.

A wholly synthetic municipality used to demonstrate the claim portal and the
voter lookup experience end to end, against the live database, without touching
a real candidate's record.

    python demo/demo_candidates.py seed
    python demo/demo_candidates.py teardown
    python demo/demo_candidates.py status

WHY IT LIVES HERE AND NOT IN data/
    Pepperland is not a registered jurisdiction. It is deliberately kept out of
    data/<slug>/ and out of data/jurisdictions.csv so the pipeline's own
    reporting — build_jurisdictions_overview.py, build_data_gaps_report.py, the
    known-sources registry — never counts a fictional city among the real ones.
    The database rows are the artifact; this script is the only thing that
    creates them, and `teardown` removes every one.

HOW A FAUX POSTAL CODE RESOLVES
    api.geocode() is cache-first: it reads geocode_cache before it calls Google.
    Seeding a row there for DEMO_POSTAL_CODE means the lookup never leaves our
    infrastructure, costs nothing, and returns the same point every time. Z is
    not used as a first letter by Canada Post, so Z0Z0Z0 can never collide with
    a real postal code a voter might type.

WHERE IT SITS ON THE MAP
    A small box near Bancroft, Ontario. That location was chosen because a real
    federal riding and a real provincial riding cover it while no registered
    municipality does — verified by ST_Intersects against every loaded district
    before the box was fixed. So a lookup on the demo postal code returns a real
    MP, a real MPP, and Pepperland's own council: the full three-level voter
    experience, with no possibility of shadowing a real city's ward.

THE SHARED EMAIL IS THE POINT
    All five candidates carry the same address. The claim flow compares the
    typed address against raw_candidates.email in memory and then mails the link
    to the stored address and nowhere else, so one inbox receives the claim link
    for whichever of the five you claim.
"""

import argparse
import os
import sys
import unicodedata
import uuid as uuidlib

import psycopg2
from dotenv import load_dotenv

load_dotenv()

SLUG = "ca_on_pepperland"
DEMO_POSTAL_CODE = "Z0Z0Z0"
DEMO_EMAIL = "ali.syed@parliamentapp.ca"

# The demo ward, and the point the postal code resolves to (its centre).
WARD_ID = "Ward 1"
WARD_WKT = (
    "POLYGON((-77.88 45.02,-77.82 45.02,-77.82 45.08,-77.88 45.08,-77.88 45.02))"
)
DEMO_LAT, DEMO_LON = 45.05, -77.85

# The pinned candidate namespace from .claude/agents/candidate-consolidation.md.
# Reused here rather than invented so a demo uuid is generated by exactly the
# same rule as a real one — the property the whole claim flow rests on.
CANDIDATE_NS = uuidlib.UUID("c4a7d1e2-9f3b-5c6d-8e1a-2b3c4d5e6f7a")

# The incumbent pipeline's namespace was never pinned to a constant (each run
# invented its own), so there is nothing to match. The two demo incumbents use
# the candidate namespace with a distinct key shape; they are placeholders whose
# only job is to give the mayoral race its title and the ward a sitting member.
POLITICIAN_KEY_PREFIX = "politician|"


def _cuuid(first: str, last: str, role_scope: str, district_id: str) -> str:
    """Deterministic candidate uuid — the pinned formula, unchanged."""
    key = unicodedata.normalize(
        "NFC", f"{SLUG}|{first}|{last}|{role_scope}|{district_id}"
    ).casefold().strip()
    return str(uuidlib.uuid5(CANDIDATE_NS, key))


def _puuid(first: str, last: str) -> str:
    key = unicodedata.normalize(
        "NFC", f"{POLITICIAN_KEY_PREFIX}{SLUG}|{first}|{last}"
    ).casefold().strip()
    return str(uuidlib.uuid5(CANDIDATE_NS, key))


# ── The roster ───────────────────────────────────────────────────────────────
# Two contest the mayoralty, three contest the ward, so both a jurisdiction-wide
# race and a district race render, and neither is uncontested.
#
# Mayoral rows are role_scope='role' with no district, which is what the
# raw_candidates scope/district constraint requires and what makes the races
# endpoint title their race from the sitting executive's own word for the office.
CANDIDATES = [
    ("John",   "Lennon",     "role",     None,    None),
    ("Paul",   "McCartney",  "role",     None,    None),
    ("George", "Harrison",   "district", WARD_ID, WARD_ID),
    ("Ringo",  "Starr",      "district", WARD_ID, WARD_ID),
    ("Pete",   "Best",       "district", WARD_ID, WARD_ID),
]

# The sitting council. Two rows only: the mayor supplies the mayoral race title
# ("Mayor of Pepperland"), the councillor keeps the municipal section of the
# results page from rendering empty above the candidates.
INCUMBENTS = [
    ("George", "Martin", "role",     None,    None,    "executive",      "Mayor"),
    ("Billy",  "Shears", "district", WARD_ID, WARD_ID, "representative", "Councillor"),
]


def connect():
    url = os.getenv("SUPABASE_DB_URL")
    if not url:
        sys.exit("SUPABASE_DB_URL is not set. Cannot connect to the database.")
    conn = psycopg2.connect(url)
    conn.autocommit = False  # every mode below is one transaction
    return conn


# ── seed ─────────────────────────────────────────────────────────────────────
def seed(conn):
    cur = conn.cursor()

    cur.execute(
        """
        INSERT INTO jurisdictions (
            slug, name, level, country_code, province_code, parent_slug,
            governance_type, partisan, district_term, role_label_singular,
            role_label_plural, expected_district_count, last_election,
            election_date_set, next_election, term_duration_years,
            governance_summary
        ) VALUES (
            %s, 'Pepperland', 'municipal', 'CA', 'ON', 'ca_on',
            'ward_based', false, '4 years', 'Councillor',
            'Councillors', 1, '2022-10-24',
            true, '2026-10-26', 4,
            'DEMO JURISDICTION — NOT A REAL PLACE. Pepperland exists only to '
            'demonstrate the candidate claim portal and the voter lookup flow. '
            'Every person, ward and postal code attached to it is fictional. '
            'Created and removed by demo/demo_candidates.py.'
        )
        ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
        """,
        (SLUG,),
    )

    # One ward. ST_GeomFromText with SRID 4326 matches districts.boundary, which
    # is what the lookup's ST_Contains compares against.
    cur.execute(
        """
        INSERT INTO districts (jurisdiction_slug, external_id, name, boundary)
        VALUES (%s, %s, %s, ST_GeomFromText(%s, 4326))
        ON CONFLICT (jurisdiction_slug, external_id)
        DO UPDATE SET boundary = EXCLUDED.boundary, name = EXCLUDED.name;
        """,
        (SLUG, WARD_ID, WARD_ID, WARD_WKT),
    )

    # The faux postal code. This is what makes the demo free and deterministic:
    # geocode() finds it here and never calls Google.
    cur.execute(
        """
        INSERT INTO geocode_cache (postal_code, latitude, longitude)
        VALUES (%s, %s, %s)
        ON CONFLICT (postal_code)
        DO UPDATE SET latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude;
        """,
        (DEMO_POSTAL_CODE, DEMO_LAT, DEMO_LON),
    )

    # Incumbents are replaced wholesale rather than upserted: politicians has no
    # natural key (one person holds many role-rows), so delete-then-insert for
    # this one slug is the same thing the real export does.
    cur.execute("DELETE FROM politicians WHERE jurisdiction_slug = %s;", (SLUG,))
    for first, last, scope, did, dname, role, title in INCUMBENTS:
        cur.execute(
            """
            INSERT INTO politicians (
                uuid, jurisdiction_slug, role_scope, district_id, district_name,
                first_name, last_name, standard_role, specific_title,
                next_election, last_verified, slug
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, '2026-10-26', CURRENT_DATE, %s);
            """,
            (
                _puuid(first, last), SLUG, scope, did, dname,
                first, last, role, title,
                f"{first}-{last}".lower(),
            ),
        )

    # Candidates UPSERT on uuid rather than delete-then-insert, exactly as
    # candidate-export does, because invitations and submissions foreign-key the
    # uuid. Re-seeding therefore preserves any claim link already emailed.
    for first, last, scope, did, dname in CANDIDATES:
        cur.execute(
            """
            INSERT INTO raw_candidates (
                uuid, jurisdiction_slug, first_name, last_name, email, phone,
                role_scope, district_id, district_name
            ) VALUES (%s, %s, %s, %s, %s, NULL, %s, %s, %s)
            ON CONFLICT (uuid) DO UPDATE SET
                email = EXCLUDED.email,
                district_id = EXCLUDED.district_id,
                district_name = EXCLUDED.district_name;
            """,
            (
                _cuuid(first, last, scope, did or ""), SLUG,
                first, last, DEMO_EMAIL, scope, did, dname,
            ),
        )

    conn.commit()
    print(f"Seeded {SLUG}: 1 ward, {len(INCUMBENTS)} incumbents, "
          f"{len(CANDIDATES)} candidates, postal code {DEMO_POSTAL_CODE}.")


# ── teardown ─────────────────────────────────────────────────────────────────
def teardown(conn):
    """
    Remove every trace, in dependency order.

    submissions is deleted first and explicitly: it references raw_candidates
    with ON DELETE RESTRICT, so a cascade from jurisdictions would otherwise
    abort the moment any demo candidate had claimed their page.
    """
    cur = conn.cursor()
    uuids = [_cuuid(f, l, s, d or "") for f, l, s, d, _ in CANDIDATES]

    cur.execute("DELETE FROM submissions WHERE candidate_uuid = ANY(%s);", (uuids,))
    subs = cur.rowcount
    cur.execute("DELETE FROM invitations WHERE candidate_uuid = ANY(%s);", (uuids,))
    invs = cur.rowcount
    cur.execute("DELETE FROM raw_candidates WHERE jurisdiction_slug = %s;", (SLUG,))
    cands = cur.rowcount
    cur.execute("DELETE FROM politicians WHERE jurisdiction_slug = %s;", (SLUG,))
    pols = cur.rowcount
    cur.execute("DELETE FROM districts WHERE jurisdiction_slug = %s;", (SLUG,))
    dists = cur.rowcount
    cur.execute("DELETE FROM jurisdictions WHERE slug = %s;", (SLUG,))
    juris = cur.rowcount
    cur.execute("DELETE FROM geocode_cache WHERE postal_code = %s;", (DEMO_POSTAL_CODE,))
    geo = cur.rowcount

    conn.commit()
    print(f"Removed: {subs} submissions, {invs} invitations, {cands} candidates, "
          f"{pols} incumbents, {dists} districts, {juris} jurisdiction, {geo} postal code.")


# ── status ───────────────────────────────────────────────────────────────────
def status(conn):
    cur = conn.cursor()
    cur.execute("SELECT name FROM jurisdictions WHERE slug = %s;", (SLUG,))
    row = cur.fetchone()
    if not row:
        print(f"{SLUG} is not seeded.")
        return
    print(f"Jurisdiction: {row[0]} ({SLUG})")

    cur.execute(
        "SELECT latitude, longitude FROM geocode_cache WHERE postal_code = %s;",
        (DEMO_POSTAL_CODE,),
    )
    print(f"Postal code {DEMO_POSTAL_CODE}: {cur.fetchone()}")

    cur.execute(
        """
        SELECT c.first_name, c.last_name, c.role_scope,
               COALESCE(c.district_name, 'citywide'), c.uuid,
               i.token IS NOT NULL, s.candidate_uuid IS NOT NULL
        FROM raw_candidates c
        LEFT JOIN invitations i ON i.candidate_uuid = c.uuid
        LEFT JOIN submissions s ON s.candidate_uuid = c.uuid
        WHERE c.jurisdiction_slug = %s
        ORDER BY c.role_scope DESC, c.last_name;
        """,
        (SLUG,),
    )
    for r in cur.fetchall():
        print(f"  {r[0]} {r[1]:<12} {r[3]:<10} {r[4]}  "
              f"invited={r[5]}  claimed={r[6]}")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("mode", choices=("seed", "teardown", "status"))
    args = p.parse_args()

    conn = connect()
    try:
        {"seed": seed, "teardown": teardown, "status": status}[args.mode](conn)
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


if __name__ == "__main__":
    main()
